config/routes.rb
Rails.application.routes.draw do
  get 'interests/index'
  get 'interests/new'
  get 'interests/create'
  get 'interests/edit'
  get 'interests/update'

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :profils
  get "findpal", to: "pages#pal_finder"
  resources :interests

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'pages/view'
  get 'pages/dashboard'
  # Defines the root path route ("/")
  root 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/interest.rb
class Interest < ApplicationRecord
  belongs_to :profil
end

app/models/profil.rb
class Profil < ActiveRecord::Base
  belongs_to :user

  has_many :interests
  accepts_nested_attributes_for :interests
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profil
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # white list approach: protect every route by default
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :view

  def view
  end

  def dashboard
    @user_profile = Profil.find_by(user_id: current_user.id)
    @pal = Profil.find(params[:pal]) unless params[:pal].nil?
  end

  def pal_finder
    @user_profile = Profil.find_by(user_id: current_user.id)
    @pal = PalFinder.new(@user_profile).find_pal
    redirect_to pages_dashboard_path(pal: @pal)
  end
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController
  skip_before_action :authenticate_user!, only: :view
  before_action :set_user

  def index
    @profiles = Profil.all
  end

  def show
  end

  def new
    @profile = Profil.new
    @interest = @profile.interests.new
  end

  def create
    @profile = Profil.new(profil_params)
    # link new profil to current user
    @profile.user_id = current_user.id
    if @profile.save
      return redirect_to pages_dashboard_path
    end
    render new, status: :unprocessable_entity
  end

  def edit
    @profile = Profil.find(params[:id])
  end

  def update
    @profile = Profil.find(params[:id])
    return redirect_to pages_dashboard_path if @profile.update(profil_params)

    render edit, status: :unprocessable_entity
  end

  private

  def profil_params
    params.require(:profil).permit(:name, :wohnort, interests_attributes:[:name])
  end

  def set_user
    @user = current_user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/views/interests/create.html.erb
<h1>Interests#create</h1>
<p>Find me in app/views/interests/create.html.erb</p>

app/views/interests/edit.html.erb
<h1>Interests#edit</h1>
<p>Find me in app/views/interests/edit.html.erb</p>

app/views/interests/index.html.erb
<h1>Interests#index</h1>
<p>Find me in app/views/interests/index.html.erb</p>

app/views/interests/new.html.erb
<h1>Interests#new</h1>
<p>Find me in app/views/interests/new.html.erb</p>

app/views/interests/update.html.erb
<h1>Interests#update</h1>
<p>Find me in app/views/interests/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyHobbyPal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
  <div class="container item-align center">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/navbar" %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">

  <h1>Das ist dein Dashboard!</h1>

  <% if @user_profile != nil %>
  <h2>Willkommen zurück, <%= @user_profile.name %>!</h2>
    <h3>Deine Hobbies</h3>
    <ul>
    <% if @user_profile.interests %>
      <% @user_profile.interests.each do |interest| %>
    <li><%= interest.name %></li>
     <% end %>
    <% end %>
    </ul>
      <% if @pal %>
      <div class="container">
        <h2>Dein Kumpel heißt: <%= @pal.name  %> und wohnt in <%= @pal.wohnort  %>!</h2>
       </div>
    <% end %>
  <% end %>

  <% if @user_profile %>
    <%= link_to "Daten ändern", edit_profil_path(@user_profile), class: "btn btn-primary" %>
    <%= link_to "Finde einen Kumpel", findpal_path, class: "btn btn-success" %>
  <% else %>
    <%= link_to "Neues Profil", new_profil_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/pages/view.html.erb
<h1>Pages#view</h1>
<p>Find me in app/views/pages/view.html.erb</p>

app/views/profils/edit.html.erb
  <%= simple_form_for @profile do |f| %>
  <%= f.input :name %>
  <%= f.input :wohnort %>
    <%= f.simple_fields_for :interests do |i| %>
    <%= i.input :name, label: "Füge ein Hobby hinzu" %>
    <% end %>
  <%= f.submit %>
<% end %>

app/views/profils/index.html.erb
<h1>Hi from profils</h1>

app/views/profils/new.html.erb
<h1>Noch schnell das Formular ausfüllen ...</h1>

<%= simple_form_for @profile do |f| %>
  <%= f.input :name %>
  <%= f.input :wohnort %>
    <%= f.simple_fields_for :interests do |i| %>
    <%= i.input :name, label: "Dein Hobby" %>
    <% end %>
  <%= f.submit %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>